name: My First Action

on:
  push:
    branch: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello World, Bigsam is here!"





















