name: Multiple jobs workflow


on:
 push:
  branches: [ main ]


jobs:
 linux_check:
  runs-on: ubuntu-latest

  steps:
   - name: checking linux information
     run: |
          whoami
          pwd
          date
          uname -a
          hostname
          df -h
          free -h
          touch test-from-job1
          echo "hello from job 1" >> test-from-job1
          cat test-from-job1
          




 repository_check:
  runs-on: ubuntu-latest

  steps:
   - name: Check out Repository 
     uses: actions/checkout@v4

   - name: Checking repository information
     run: |
          tree -a
          ls -la       
          git status
          git log --oneline
          ls -l test-from-job1
          cat test-from-job1
          

         


     
  