name: My checkout test workflow

on:
 push:
  branch: [ main ]

jobs:
 checkout_test:
  runs-on: ubuntu-latest

  steps:
   - name: checkout repository
     uses: actions/checkout@v4

   - name: checking repository files and directories
     run: |
          ls -la
          date
          pwd
          git status
          git log --oneline
          touch .github/workflows/new.txt
          ls -la .github/workflows/new.txt
          cat .github/workflows/test.yml 
          